version: "3.9"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://es:9200"]
      interval: 3s
      timeout: 5s
      retries: 20
      start_period: 5s
    volumes:
      - es_data:/usr/share/elasticsearch/data
  es-init:
    depends_on:
      es:
        condition: service_healthy
    build: ./es-init
    container_name: es-init
    environment:
      ELASTICSEARCH_URL: http://es:9200
  kibana:
    depends_on:
      es:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:8.3.2
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://es:9200
    ports:
      - '5601:5601'

  retrieve:
    depends_on:
      es:
        condition: service_healthy
      es-init:
        condition: service_completed_successfully
    build: ./retrieve
    container_name: retrieve
    environment:
      MAX_GRPC_WORKERS: 2
      GRPC_PORT: 9200
      ELASTICSEARCH_URL: http://es:9200
    ports:
      - '9201:9200'
  web:
    depends_on:
      - retrieve
    build: ./web
    container_name: web
    environment:
      DJANGO_PORT: 8000
#      DEBUG: false
    ports:
      - '8000:8000'

volumes:
  es_data:
    driver: local